# Generated by Django 5.1.3 on 2024-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('playing', 'Playing'), ('finished', 'Finished')], default=None, max_length=20, null=True)),
                ('review', models.TextField(blank=True, default=None, null=True)),
                ('recommendation', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True)),
                ('studio', models.CharField(max_length=255)),
                ('genre', models.JSONField(default=list)),
                ('included', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.TextField()),
                ('recommendation', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True)),
                ('link', models.TextField()),
                ('topics', models.JSONField(default=list)),
                ('included', models.BooleanField(default=True)),
            ],
        ),
    ]
