# Generated by Django 5.1.3 on 2024-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('recommendation', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('studio', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='included',
        ),
        migrations.AlterField(
            model_name='resources',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resources',
        ),
    ]
