# Generated by Django 5.1.3 on 2024-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_games_delete_game_remove_resources_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='review',
            field=models.TextField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resources',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
